# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@stable-kf6'
    'frameworks/kdoctools': '@stable-kf6'
    'frameworks/ki18n': '@stable-kf6'
    'frameworks/kiconthemes': '@stable-kf6'
    'frameworks/kio': '@stable-kf6'
    'frameworks/kwindowsystem': '@stable-kf6'
    'frameworks/kxmlgui': '@stable-kf6'
